name: Setup
description: Boilerplate steps needed by most jobs.
inputs:
  node-version:
    description: Version of Node to use.
    required: false
    default: 16.x
  install-deps:
    description: Should deps be installed?
    required: false
    default: 'true'
  offline:
    description: Should --offline be used?
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Use Node.js ${{inputs.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.node-version}}
    - name: Enable Corepack
      run: |
        corepack enable
        echo "PnPM version is $(pnpm --version)"
      shell: bash
    # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
    - name: Get current month
      id: date-month
      shell: bash
      run: |
        DATE=$(date +'%Y-%m')
        echo "$DATE"
        echo "date_month=$DATE" >> $GITHUB_OUTPUT
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{steps.date-month.outputs.dateMonth}}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-${{steps.date-month.outputs.date_month}}
    - name: Install Dependencies
      run: pnpm install ${{ (inputs.offline == 'true') && format('{0}', '--offline') || format('{0}', '') }}
      shell: bash
      if: ${{inputs.install-deps}} == 'true'
