name: Release
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: prisma-labs/dripip@master
        with:
          isStable: true
          npmToken: ${{secrets.NPM_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
