name: trunk
on:
  push:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
  test:
    needs: setup
    uses: ./.github/workflows/test.yaml
  # https://github.community/t/how-can-i-test-if-secrets-are-available-in-an-action/17911/10
  checkNpmTokenSet:
    name: Check if NPM_TOKEN secret is set
    runs-on: ubuntu-latest
    outputs:
      isNpmTokenSet: ${{ steps.checkNpmTokenSet.outputs.isNpmTokenSet }}
    steps:
      - name: Check if NPM_TOKEN secret is set
        id: checkNpmTokenSet
        run: |
          echo "isNpmTokenSet: ${{secrets.NPM_TOKEN != ''}}"
          echo "::set-output name=isNpmTokenSet::${{secrets.NPM_TOKEN != ''}}"
  release-canary:
    needs: [test, checkNpmTokenSet]
    if: needs.checkNpmTokenSet.outputs.isNpmTokenSet == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: prisma-labs/dripip@master
        with:
          npmToken: ${{secrets.NPM_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
