name: trunk
concurrency: trunk
on:
  push:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: ./.github/actions/setup
